### ISSUE TITLE
Android build fails when using eas-cli but not when using expo-cli

### ISSUE THREAD

**Issue by pdandradeb** [expo/eas-cli#853] opened 2021-12-15 14:31 UTC
### Summary

Maybe is related with https://github.com/expo/eas-cli/issues/558. Previously, building with `eas` finished "successfully" but missing all but one intent filter. Now the build fails when using `eas` but not with `expo-cli`.

Could you tell something by the error output? I'm trying to identify by putting module by module in new app but it has been pretty difficult so far.

### Managed or bare?

managed

### Environment

  EAS CLI 0.41.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.2/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.2/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.41.0
      expo-cli: 5.0.0
    Project workflow: managed

### Error output

```
> Task :app:processReleaseMainManifest FAILED
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
[stderr] /root/workingdir/build/android/app/src/main/AndroidManifest.xml:14:13-88 Error:
[stderr] 	Attribute meta-data#org.unimodules.core.AppLoader#react-native-headless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unimodules-react-native-adapter] AndroidManifest.xml:14:13-88
[stderr] 	is also present at [:expo-modules-core] AndroidManifest.xml:14:13-86 value=(expo.modules.adapters.react.apploader.RNHeadlessAppLoader).
[stderr] 	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:12:9-14:91 to override.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processReleaseMainManifest'.
[stderr] >
[stderr] Manifest merger failed : Attribute meta-data#org.unimodules.core.AppLoader#react-native-headless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unimodules-react-native-adapter] AndroidManifest.xml:14:13-88
[stderr]   	is also present at [:expo-modules-core] AndroidManifest.xml:14:13-86 value=(expo.modules.adapters.react.apploader.RNHeadlessAppLoader).
[stderr]   	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:12:9-14:91 to override.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 7m 57s
```

### Reproducible demo or steps to reproduce from a blank project

Here's the "blank" project that I used to identify the first issue with intent filters and I'm updating it to identify this new one.

`git clone https://github.com/appjusto/appjusto-test`
`eas build --profile preview`

**Comment by semanticdreamer** [comment] 2021-12-18 09:33
running into the same issue :-/

**Comment by pdandradeb** [comment] 2022-01-10 15:34
@brentvatne @dsokal hey guys, sorry to ping you but could you check this? I can only build our app using expo build.

**Comment by brentvatne** [comment] 2022-01-11 04:14
hey @pdandradeb! this page is dedicated to helping folks debug their issues when using eas build: https://docs.expo.dev/build-reference/troubleshooting/

let me know how that goes

**Comment by brentvatne** [comment] 2022-01-11 22:19
i'm unable to reproduce the issue with the repository provided. build succeeded both locally and on eas build. closing the issue for now, please create a new one with a reproducible example.

also, your log output shows that you're using sdk 43 - i'd suggest updating to 44 where we improved handling of intents.

**Closed by brentvatne** 2022-01-11 22:19 UTC
Labels: bug

**Comment by pdandradeb** [comment] 2022-01-21 13:40
Hey @brentvatne, I've updated to SDK 44 and the build works but the issue https://github.com/expo/eas-cli/issues/558 remains. I'll add some comments there.
