### ISSUE TITLE
Error: git exited with non-zero code: 1

### ISSUE THREAD

**Issue by imhazige** [expo/eas-cli#967] opened 2022-02-10 06:21 UTC
### Summary

I am using biterise to run android build with command `$ /Users/vagrant/git/project_git/node_modules/.bin/eas build -p android --profile develop --wait --non-interactive --local --output android.aab`.

But it always throw git Error: git exited with non-zero code: 1

I have tested with 
yarn eas build:inspect -v -p android -s pre-build --profile $STAGE_NAME -o ./abc
yarn eas build:inspect -v -p android -s archive--profile $STAGE_NAME -o ./abc
yarn eas build:inspect -v -p android -s post-build --profile $STAGE_NAME -o ./abc

All have no problem.

The git and node version are all good.

What I doubt is that biterise will create a git folder underneath the Home folder, will this cause the problem?

### Managed or bare?

managed

### Environment

$ /Users/vagrant/git/project_git/node_modules/.bin/eas build -p android --profile develop --wait --non-interactive --local --output android.aab
    Error: git exited with non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Error output

$ /Users/vagrant/git/project_git/node_modules/.bin/eas build -p android --profile develop --wait --non-interactive --local --output android.aab
    Error: git exited with non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproducible demo or steps to reproduce from a blank project

{
    "cli": {
        "version": ">= 0.47.0"
    },
    "build": {
        "develop": {
            "distribution": "store",
            "releaseChannel": "develop_android_1.0.0_2",
            "env": {
                "UNIVERSAL_LINK_HOST": "webapp.dev.[REDACTED].com",
                "APP_VERSION": "1.0.0",
                "APP_BUILD_NUMBER": "2",
                "APP_NAME": "FMClarity DEVELOP",
                "APP_SLUG": "[REDACTED]_develop",
                "APP_IOS_BUNDLE_ID": "com.[REDACTED].develop",
                "APP_ANDROID_PACKAGE": "com.[REDACTED].develop",
                "APP_ANDROID_FCM_JSON_PATH": "/Users/vagrant/git/project_git/.buildkite/develop-google-services.json",
                "APP_API_BASEURL": "https://api.dev.[REDACTED].com",
                "BUGSNAG_API_KEY": "[REDACTED]",
                "APP_DEBUG_APP_JSON": "true",
                "RELEASE_CHANNEL": "develop_android_1.0.0_2",
                "MY_BUILD_PROFILE": "develop"
            }
        }
    },
    "submit": {
        "production": {}
    }
}

**Comment by wkozyra95** [comment] 2022-02-10 11:22
can you run that build with env `DEBUG=*` ?

**Comment by imhazige** [comment] 2022-02-10 23:58
Hey, @wkozyra95 

this is the output
Error: git exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/vagrant/git/project_git/node_modules/eas-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
    ...
    at spawnAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at GitNoCommitClient.trackFileAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/build/vcs/clients/git.js:121:41)
    at createEasJsonAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/build/build/configure.js:88:37)
    at async configureAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/build/build/configure.js:31:5)
    at async ensureProjectConfiguredAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/build/build/configure.js:25:5)
    at async runBuildAndSubmitAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/build/build/runBuildAndSubmit.js:34:5)
    at async Build.runAsync (/Users/vagrant/git/project_git/node_modules/eas-cli/build/commands/build/index.js:31:9)
    at async Build._run (/Users/vagrant/git/project_git/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:52:22)
    at async Config.runCommand (/Users/vagrant/git/project_git/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:226:25)
    at async Object.run (/Users/vagrant/git/project_git/node_modules/eas-cli/node_modules/@oclif/core/lib/main.js:73:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by imhazige** [comment] 2022-02-11 01:39
Hey, @wkozyra95 

Thank you for the DEBUG option. I found it because the eas.json is not generated. After generated, the problem disappear.

But the error hint really make no sense. lol

**Comment by imhazige** [comment] 2022-02-11 02:47
@mitramejia 

I create the eas.json by bash. after created it, it works.

Anyway, set DEBUG=* will help.

**Comment by wkozyra95** [comment] 2022-02-11 13:53
@mitramejia did you run build with `DEBUG=*` option? if yes please post a stacktrace.

**Comment by imhazige** [comment] 2022-02-11 22:10
> @imhazige eas.json is created automatically by the cli, `git exited with non-zero code: 1` in your case is thrown when calling `git add` on `eas.json`. The only case I was able to reproduce error like yours, was if you run build inside git repository, but package.json is outside of the repo.
> 
> Also if eas.json di not exist this command was incorrect because there was no profile develop yet, `eas build -p android --profile develop --wait --non-interactive --local --output android.aab` .

In my case, I created the eas.json by bash. the develop exists in the json, you can see it in the log I pasted.

**Comment by mauricedoepke** [comment] 2022-03-08 22:00
I have the issue as well. Here my log output:

```
maurice-pascaldopke@MauricescalsMBP mobile % eas build --platform ios --profile production
  config reading core plugin /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/package.json +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/oclif.manifest.json +0ms
  config:eas-cli using manifest from /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/oclif.manifest.json +0ms
  config reading user plugins pjson /Users/maurice-pascaldopke/.local/share/eas-cli/package.json +0ms
  config loadJSON /Users/maurice-pascaldopke/.local/share/eas-cli/package.json +0ms
  config loading plugins [
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-help',
  '@expo/plugin-warn-if-update-available'
] +0ms
  config reading core plugin /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/package.json +0ms
  config reading core plugin /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help/package.json +0ms
  config reading core plugin /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/package.json +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config loadJSON /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config:@oclif/plugin-autocomplete using manifest from /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  config:@oclif/plugin-help using manifest from /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config:@expo/plugin-warn-if-update-available using manifest from /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config config done +3ms
  config start init hook +0ms
  eas:@expo/plugin-warn-if-update-available:hooks:init start (require) /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/lib/hooks/init/check-update.js +0ms
  eas:@expo/plugin-warn-if-update-available:hooks:init done +2ms
  config init hook done +12ms
  config runCommand build [ '--platform', 'ios', '--profile', 'production' ] +0ms
  config:eas-cli (require) /Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/commands/build +325ms
  config start prerun hook +303ms
  config prerun hook done +0ms
  eas:build init version: @oclif/core@1.3.1 argv: [ '--platform', 'ios', '--profile', 'production' ] +0ms
✔ Linked to project ****************************
Specifying "ios.bundleIdentifier" in app.config.ts is deprecated for bare workflow projects.
EAS Build depends only on the value in the native code. Please remove the deprecated configuration.
✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … ****************************
› Restoring session /Users/maurice-pascaldopke/.app-store/auth/mauricedoepke@outlook.de/cookie
› Team ****************************
› Provider ****************************
✔ Logged in Local session
✔ Bundle identifier registered ****************************
✔ Synced capabilities: No updates
✔ Synced capability identifiers: No updates
✔ Fetched Apple distribution certificates
✔ Fetched Apple provisioning profiles

Project Credentials Configuration

Project                   ****************************
Bundle Identifier         ****************************
                          
App Store Configuration   
                          
Distribution Certificate  
Serial Number             ****************************
Expiration Date           Thu, 03 Nov 2022 15:45:16 GMT+0100
Apple Team                ****************************
Updated                   4 months ago
                          
Provisioning Profile      
Developer Portal ID       ****************************
Status                    active
Expiration                Thu, 03 Nov 2022 15:45:16 GMT+0100
Apple Team                ****************************
Updated                   1 day ago
                          
All credentials are ready to build ****************************

✔ Push Notifications setup for ****************************
Error: git exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (node:events:640:26)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:520:28)
    at Pipe.<anonymous> (node:net:687:12)
    ...
    at spawnAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at GitNoCommitClient.trackFileAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/vcs/clients/git.js:121:41)
    at writeExpoPlistAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/ios/UpdatesModule.js:26:37)
    at async syncUpdatesConfigurationAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/ios/UpdatesModule.js:15:5)
    at async syncProjectConfigurationAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/ios/syncProjectConfiguration.js:15:13)
    at async Object.syncProjectConfigurationAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/ios/build.js:51:13)
    at async attemptEvent (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/build.js:32:56)
    at async withAnalyticsAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/analytics/common.js:7:24)
    at async prepareBuildRequestForPlatformAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/build.js:32:5)
    at async prepareIosBuildAsync (/Users/maurice-pascaldopke/.nvm/versions/node/v16.14.0/lib/node_modules/eas-cli/build/build/ios/build.js:45:12)
```

**Comment by mauricedoepke** [comment] 2022-03-09 13:02
I tried the following to solve this issue:
- updating eas client
- updating git
- deleting whole project folder and do a fresh clone

But I still have the error.

I only get the error with ios builds though. 
Android ones work like a charm.

**Comment by wkozyra95** [comment] 2022-03-09 13:49
do you have Expo.plist file gitignored? (btw I'm assuming that it's a bare project)

**Comment by mauricedoepke** [comment] 2022-03-09 14:57
I could solve the issue for me.
After deleting the ios folder it worked.
Apparently we accidentally comitted it into our repo.

No I did not have Expo.plist ignored. Should I? The .expo folder is in my gitignore though.

I am not sure what your definition of bare is. I started with a managed project and then switched to eas, but never ejected.

**Comment by wkozyra95** [comment] 2022-03-09 15:16
project is bare when android and ios directory exists and it's not gitignored

> No I did not have Expo.plist ignored. Should I? 

no, but error happened when cli attempted to run `git add` on `Expo.plist` just after creating it, If we know that file existed then the only explanation I'm aware of could be that that file (or directory) was gitingored

>  I started with a managed project and then switched to eas, but never ejected.

If you had android nad ios directory then you did. It happens if you run `expo prebuild` `expo eject` or `expo run:ios/android`

**Comment by mauricedoepke** [comment] 2022-03-09 15:20
The file did not exist in my project. I guess someone accidentally did this prebuild and left a corrupted directory in the repo.

I guess my solution will then be to put ios and android folders into the git ignore. 

Thanks for your help

**Comment by wkozyra95** [comment] 2022-04-08 08:47
I was not able to reproduce the issue, closing the issue for now. If you are experiencing this problem, please create a new issue with a reproducible example.

**Closed by wkozyra95** 2022-04-08 08:47 UTC
Labels: bug

**Comment by ksgy** [comment] 2022-09-13 11:20
Could be an XCode update...

Opening XCode and accepting the new EULA solved the issue above 🤔

**Comment by unip** [comment] 2022-09-17 03:59
> Could be an XCode update...
> 
> Opening XCode and accepting the new EULA solved the issue above 🤔

this works for me 👍

**Comment by PiotrSzlagura** [comment] 2023-03-10 09:49
I have the exact same issue, after running `eas update` with `DEBUG=*` i narrowed it down to `dist/metadata.json` not being created (I'm running it on Gitlab CI). Is there any circumstance in which this file is not created? Locally when I remove dist/ and run `eas update` it gets created and everything works (I did my best to recreate environment which is used on gitlab worker machine), so I don't really understand what am I doing wrong here.

**Comment by appsgenie** [comment] 2023-06-23 03:33
I am also getting this error around spawnAsync, but this is for a local ios EAS development build. 
I see suggestion to run DEBUG=* to get more info? How do I do that?
