### ISSUE TITLE
`eas build`: Build failed - Could not find target 'app' in project.pbxproj

### ISSUE THREAD

**Issue by aguidad** [expo/eas-cli#1357] opened 2022-09-14 09:16 UTC
### Build/Submit details page URL

https://expo.dev/accounts/guidad/projects/khotoba/builds/dc117551-4e2a-4a38-b1c9-b15496583ff7

### Summary

when I used eas to build ios `eas build --profile development --platform ios`, i got error in xcode configuration section said that Could not find target 'app' in project.pbxproj

```bash
Build section: Configure Xcode project

Configuring Xcode project
Assigning provisioning profile '*[expo] `bundleIdentifier` AdHoc xxxxxxxxxxxx' (Apple Team ID: XXXXXXXX) to target 'app'
Could not find target 'app' in project.pbxproj
```

### Managed or bare?

Managed

### Environment

npx expo-env-info:
```bash
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      expo: ^43.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: ~0.17.1 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.2
    Expo Workflow: managed
```
expo doctor:
```bash
🎉 Didn't find any issues with the project!
```

### Reproducible demo or steps to reproduce from a blank project

eas build

**Comment by wkozyra95** [comment] 2022-09-15 13:08
The issue is caused by the fact that your app name does not contain alphanumeric characters and we use that value to resolve target name. It's possible that this case might be fixed in latest eas-cli. Can you verify that?

**Comment by aguidad** [comment] 2022-09-15 20:53
Yes, i confirm it, the issue was due to the app name.

**Comment by YukiOmori** [comment] 2022-09-16 05:10
@wkozyra95 @aguidad 
Same here.

Could you please tell me where to change app name?

I change my app name from "app-name" to "appname" in app.config.js(ts) but the error remains.
(My eas-cli version is 2.1.0)

**Closed** 2022-09-16 13:22 UTC

**Comment by wkozyra95** [comment] 2022-09-16 13:30
@YukiOmori In this case issue was happening because the app name was using only non-ASCII characters, if your app is named appname and you are seeing a similar error please open an issue and provide all the necessary information.

**Comment by felippewick** [comment] 2022-09-24 07:58
Why is this error caused in some builds and others not? I have no issues with app-dev but with app-stg.

**Comment by wkozyra95** [comment] 2022-09-26 10:34
@felippewick If you have problems with app named app-dev or app-stg then it's not related to this issue. As I mentioned in my previous comment this problem affects only apps with non-ASCII names

**Comment by nakazato-r** [comment] 2022-10-21 09:07
@wkozyra95 I am also having the same problem.
I get the same error when I set the name of the application as "あいうえお12345".
Is it possible to create a build of the app with the combination of "non-ASCII characters" + "ASCII characters"?

**Comment by okamop** [comment] 2022-10-25 08:13
I have the same problem.
Any progress on this issue ?

**Comment by okamop** [comment] 2022-10-26 07:24
For iOS only, the app display name could be displayed in non-ASCII characters.
Changed CFBundleDisplayName in InfoPlist in ConfigPlugin.

`withIOSDisplayName.js`

```
const {withInfoPlist} = require('@expo/config-plugins');

module.exports = function withIOSDisplayName(config, displayName) {
  return withInfoPlist(config, (config) => {
    config.modResults.CFBundleDisplayName = displayName;
    return config;
  });
};
```

`app.json`

```
{
  plugins: [
    ['./withIOSDisplayName', 'non-ascii-characters'],
  ]
}
```

**Comment by yzhe554** [comment] 2022-12-13 00:05
Hi @aguidad , we are facing the same issue, can I ask how did you fix it?

**Comment by yzhe554** [comment] 2022-12-13 20:42
Thanks @aguidad , we are using English, it must be something else for us. Really weird that dev build is working.

**Comment by aguidad** [comment] 2022-12-13 22:16
@yzhe554 if you have a mac, you can build it locally to find the correct issue.

**Comment by EricHasegawa** [comment] 2023-03-15 19:25
Having the same issue -> our name is 100% just ASCII characters (sanctuarymobile) and we get this error, what possible places could be setting the name? We can't find "sanctuarymobile" anywhere in our repositories or settings, where could it be coming from?

**Comment by frederikocmr** [comment] 2023-04-18 14:39
Hello, I had the same problem after renaming my app.

What worked for me was running `npx expo prebuild --platform ios --clean` and then the eas build command, for example `eas build --profile development --platform ios`. 

This generates a /ios folder locally and then you can check yourself the files. It also skips the prebuild step saying: "Skipped running "expo prebuild" because the "ios" directory already exists.".

**Comment by ItsaMeTuni** [comment] 2025-05-22 12:34
I tried the above solutions and nothing worked for me. It turns out putting `app.json` and `eas.json` in `.gitignore` (seems kinda retarded, yes, but I have a legitimate reason to do this) causes this issue as well, so I just removed them from `.gitignore` and it went back to normal.

**Comment by uguraktas** [comment] 2025-08-17 20:25
I have same problem And the suggestions above did not solve my problem.
