### ISSUE TITLE
3rd party NPM store suddenly fails on expo prebuild Android

### ISSUE THREAD

**Issue by rasck** [expo/eas-cli#918] opened 2022-01-18 12:53 UTC
### Build/Submit details page URL

https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/f8af6b6a-e63c-40ba-993b-50acab67b712

### Summary

Our Android builds suddenly fails in prebuild step. I've tried building both with our CI and a [preview build](https://forums.expo.dev/t/eas-pre-build-fails-with-azure-npm-repository/60912)

We have for a long time used azure artifacts as our package repository, and our azure artifacts store upstream npmjs.com

This is our .npmrc file:
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=personal_access_token
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry  
always-auth=true
```

The installation step works. It should only work if the .npmrc file is correctly setup. Has something changed in prebuild step since 10th of Jan 2022, where we had our last successful build?

### Managed or bare?

Managed

### Environment

EAS CLI 0.44.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.34.1. - /mingw64/bin/git
    npmPackages:
      expo: 43.0.0 => 43.0.0
      expo-updates: 0.10.15 => 0.10.15
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Project workflow: managed

### Error output

```
Unexpected response: Unauthorized. From url: https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/expo-template-bare-minimum/-/expo-template-bare-minimum-43.0.13.tgz
```

### Reproducible demo or steps to reproduce from a blank project

* [Setup npm with azure artificats](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=azure-devops&tabs=Windows)
* [Setup npmjs.com as upstream source ](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/upstream-sources?view=azure-devops)
* [publish a package to azure](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/publish?view=azure-devops), e.g. `my-package` at version 1.0.0.
* Create a new expo project
* use the package in package.json, `"my-package": "1.0.0"`,
* setup .npmrc file (replace personal_access_token with your token)
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=personal_access_token
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry  
always-auth=true
```
* create a preview build with eas.json
```
"preview": {
      "android": {
        "buildType": "apk",
      },
      "releaseChannel": "preview"
 }
```
* run `eas build --platform android --profile=preview`

**Comment by dsokal** [comment] 2022-01-18 15:45
It looks to me like a configuration issue on your side. 

- Could you start a fresh Docker container `docker run -it node /bin/bash`, add the .npmrc there and try to run `npm install expo-template-bare-minimum` inside the container? If it fails then this is the reason it fails on EAS Build.
- Could you please link an EAS Build build that was successful before?

**Comment by rasck** [comment] 2022-01-19 07:37
Thank you for your quick reply!

* Great idea with docker. Didn't think of that at all. It works (i still think we would fail at the install dependencies step, before prebuild, if we had an error with .npmrc file):
![image](https://user-images.githubusercontent.com/11956809/150083361-c4c1a8d5-0a35-4eb9-9587-905d3560de4e.png)

* [Last successfull build using upstream approach](https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/a2d8af1f-1d34-4b6f-8e31-4783e0c9f8e0)

The issue still stands with 3rd party NPM repo that upstreams npmjs.com. But I think we will be using scoped moving forward:
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/fm.mobile.common.next/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/fm.mobile.common.next/npm/registry/:_password=PTA
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/fm.mobile.common.next/npm/registry/:email=not-used@example.com
; we only use this registry for self developled packages. By using '@ntidevel' scope npm will know this.
@ntidevel:registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/fm.mobile.common.next/npm/registry/ 
always-auth=true
```
In package.json `"@ntidevel/fm-mobile-common": "1.0.0",`

[successfull build today using scoped approach instead of upstream](https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/0f60bda5-ef3c-4246-b2db-41063ded2593)

**Comment by wkozyra95** [comment] 2022-01-19 09:51
I noticed that you are using yarn, can you check the same scenario in docker but instead `npm install` run `yarn add`

Also I'm not sure if this intended or bug, but registry sometimes might require trailing slash, it should be
`registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/`
instead of
`registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry`

are you using any vpns to connect to that registry or is it available directly?

**Comment by rasck** [comment] 2022-01-19 09:57
If you are interested in the `package-lock.json` generated in the docker image:
[package-lock.zip](https://github.com/expo/eas-cli/files/7895992/package-lock.zip)
Its over 17.000 lines, but here is also some of it:
```
  "name": "npmtest",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "npmtest",
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "expo-template-bare-minimum": "^44.0.11"
      }
    },
...
  "node_modules/expo-template-bare-minimum": {
      "version": "44.0.11",
      "resolved": "https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/expo-template-bare-minimum/-/expo-template-bare-minimum-44.0.11.tgz",
      "integrity": "sha1-o98+3y7vxnKplkdydqeBxIfb1Q0=",
      "dependencies": {
        "expo": "~44.0.2",
        "expo-splash-screen": "~0.14.1",
        "expo-status-bar": "~1.2.0",
        "react": "17.0.1",
        "react-dom": "17.0.1",
        "react-native": "0.64.3",
        "react-native-web": "0.17.1"
      }
    },
...
```

**Comment by rasck** [comment] 2022-01-19 09:59
I didn't see the last comment, i will try with yarn

**Comment by rasck** [comment] 2022-01-19 10:19
@wkozyra95 it also works with yarn:

I started a new image

![image](https://user-images.githubusercontent.com/11956809/150110346-23de7919-0fd5-4eeb-8c26-b2f5d2401de5.png)

![image](https://user-images.githubusercontent.com/11956809/150110448-bd5a3383-d894-4e72-ab47-471baf20c88f.png)

[yarn_lock.zip](https://github.com/expo/eas-cli/files/7896144/yarn_lock.zip)

From the yarn lock file
```
expo-template-bare-minimum@^44.0.11:
  version "44.0.11"
  resolved "https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/expo-template-bare-minimum/-/expo-template-bare-minimum-44.0.11.tgz#a3df3edf2eefc672a996477276a781c487dbd50d"
  integrity sha1-o98+3y7vxnKplkdydqeBxIfb1Q0=
  dependencies:
    expo "~44.0.2"
    expo-splash-screen "~0.14.1"
    expo-status-bar "~1.2.0"
    react "17.0.1"
    react-dom "17.0.1"
    react-native "0.64.3"
    react-native-web "0.17.1"
```

**Comment by wkozyra95** [comment] 2022-01-19 12:06
> I will try with trailing slash. It has worked without it though

yarn is using registry from yarn.lock so the value you are specifying in .npmrc is only respected when you run yarn add, that is way  yarn install might have worked but it;s failing when prebuild command on eas build worker is trying to install some package

**Comment by rasck** [comment] 2022-01-19 12:59
Makes sense. I tried with trailing slash (and i think we have always used that, i accidently removed it while debugging this)

* I tried again from our repo with following .npmrc file
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=PTA
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Commont/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/ 
                        
always-auth=true
```

* i removed the yarn.lock file, and ran `yarn` to install it again

* Then `eas build --platform android --profile=preview`

[The dependencies step succeeded but build failed again at prebuild](https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/ef580d06-b6ab-48ea-9727-db824eeddc43)

**Comment by rasck** [comment] 2022-01-19 13:06
I tried for debugging purposes to mess with up the .npmrc file. [Then the `Install dependencies` step fails](https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/c62f1d81-927c-403e-86b9-e6902059bb55)

In this case i omitted the `always auth=true`
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=PTA
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Commont/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/ 
```

**Comment by wkozyra95** [comment] 2022-01-19 13:39
`Commont` -> `Common`

**Comment by rasck** [comment] 2022-01-20 09:47
@wkozyra95 tried again:

[Prebuild fails with what i think is correct .npmrc file](https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/bed6d6cc-f04c-4a5c-a175-548cea0a074f):
.npmrc
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=PTA
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/ 
                        
always-auth=true
```

[Install dependencies step will fail if .npmrc is not correctly setup](https://expo.dev/accounts/ntimhe/projects/fm-tasks/builds/e14af7ad-2b82-4244-bc1d-a8ced84f99fa):
.npmrc (omitted `always-auth=true` to make .npmrc fail)
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=PTA
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/ 
```

I don't know if there is still something i have misunderstod about the yarn.lock file that can make the `Install dependencies` step succeed but not the `prebuild` step. 

I realized the `expo-template-bare-minimum` is not one of our dependencies, but a dependency of the `prebuild` step. This is our flow:

1. We commit to our repo this version of the .npmrc file:
```
registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/ 
                        
always-auth=true
```
2. Our CI add the auth lines to the .npmrc file:
```
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:username=VssSessionToken
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:_password=PTA
//pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/:email=not-used@example.com

registry=https://pkgs.dev.azure.com/ntidevel/MDOCFM/_packaging/FM.Mobile.Common/npm/registry/ 
                        
always-auth=true
```
3. Our CI runs EAS build. We use the new flow with eas.json where our CI send uncommited changes to eas build servers
4. That's why the `Install dependencies` step works

Is the same updated and uncommitted .npmrc file send to the prebuild agent (if that is a new agent)?

**Comment by rasck** [comment] 2022-01-20 13:13
I have now fully converted our app to use the scoped approach instead of upstream/proxy. If you want me to further debug the upstream approach im a happy to help. But otherwise i have no more interest in this issue.

Thank you for taking your time and thanks for the awesome product you guys a building 🎸

**Comment by PMalaret** [comment] 2022-02-11 08:57
I have the same problem.
"eas build" works perfectly up to the "prebuild" step.
I tried different eas-cli versions and it happens in all of them.

With "expo build" it works as usual.

The error, it is strange because it can install dependencies in the "Install dependencies" step.
```
Prebuilding managed project
- Creating native project directories (./ios and ./android) and updating .gitignore
[stderr] [18:06:11] Unexpected response: Unauthorized. From url: <url>/npm/registry/expo-template-bare-minimum/-/expo-template-bare-minimum-43.0.13.tgz
- Creating native project directories (./ios and ./android) and updating .gitignore
✖ Failed to create the native project.
[18:06:11] You may want to delete the `./ios` and/or `./android` directories before trying again.
bash exited with non-zero code: 1
```

**Comment by wkozyra95** [comment] 2022-02-11 09:34
> The error, it is strange because it can install dependencies in the "Install dependencies" step.

yarn is ignoring registry configuration when installing based on yarn.lock, registry in npmrc is only respected when it needs to install sth that is not specified in a lockfile.

I assume `<url>` section is URL to your registry?
Is your private registry proxying real npm registry or is it locked somehow?
Did you try configuring your npmrc only to specific scope?

**Comment by PMalaret** [comment] 2022-02-11 13:08
Yes, <url> is the 3rd party registry.
It's the Azure Artifacts registry.

**Comment by wkozyra95** [comment] 2022-02-17 09:45
HI we identified the issue, the error is caused by the fact that `expo prebuild` is using `npm view` to resolve URL to the archive, but it's not downloaded using npm so authentication info is not included.

Using scoped registries works because in that case `npm view` is returning URL to the public registry

**Comment by PMalaret** [comment] 2022-02-25 17:10
Sorry I don't understand it well.

**Comment by wkozyra95** [comment] 2022-02-25 17:26
it's an EAS issue
but you can still make it work if you use your private registry only for scoped packages

**Comment by PMalaret** [comment] 2022-02-25 17:37
Ok! Thank you!

**Comment by louislatreille** [comment] 2022-05-03 18:22
I ran into the same issue, and eventually made it work by using scoped packages. I think it would be very useful to update the docs with that information: https://docs.expo.dev/build-reference/private-npm-packages/#using-private-packages-published-to-npm

**Comment by wkozyra95** [comment] 2022-08-10 12:41
Closing, this issue was fixed a while ago.

**Closed by wkozyra95** 2022-08-10 12:41 UTC
Labels: needs more info
