### ISSUE TITLE
Add reminder to bump buildNumber / versionCode BEFORE building  

### ISSUE THREAD

**Issue by bbenson09** [expo/eas-cli#892] opened 2022-01-06 03:46 UTC
### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by bbenson09** [comment] 2022-01-06 03:50
It's easy to build without remembering to increase the buildNumber or versionCode, only for the build to get rejected by the respective app store in `eas submit`. This could be avoided (and expo could save build resources) by including a message like:

`Are you sure you wish to build project with buildNumber x and versionCode y`?

**Comment by kbrandwijk** [comment] 2022-01-07 08:44
I would even go further than that, and suggest that if `distribution` is set to `store`, we might actually check if that build number has been submitted to TestFlight already (Apple only), and for other builds, we could check if there was a past _submission_ with the same build version (more accurate), or a past _build_ (less accurate, but not all builds are submitted using `eas submit`).

**Comment by dsokal** [comment] 2022-01-10 09:21
I agree this could be improved somehow. However, I'm against displaying a prompt for every build. Our goal in `eas build` is to ask as few questions as possible. If there is a way to read the submitted TestFlight/Google Play build versions then this would be an ideal approach.

**Comment by kbrandwijk** [comment] 2022-04-07 16:43
Still relevant.

**Comment by matheins** [comment] 2022-05-23 18:04
**FYI** 
There is an option to auto-increment build number on builds for [Android](https://docs.expo.dev/build-reference/eas-json/#autoincrement) and [IOS](https://docs.expo.dev/build-reference/eas-json/#autoincrement-1)

**Comment by KiwiKilian** [comment] 2022-07-27 10:10
> autoIncrement option is not supported when using app.config.js

So is there any way to retrieve the latest build number which was used during an EAS build? Like a `EAS_LATEST_BUILD_NUMBER` environment variable which could then be increased in the `app.config.js`?

Or does anybody have another solution/workflow to increment the build number automatically when using `app.config.js`?

**Comment by izakfilmalter** [comment] 2022-08-04 00:59
Is there a solution for app.config.js users?

**Comment by wkozyra95** [comment] 2022-08-04 08:15
@izakfilmalter In the next eas-cli release we will start supporting autoIncrement where version is managed server-side, it will work with app.config.js

**Comment by izakfilmalter** [comment] 2022-08-04 11:59
Oh yay! Can't wait ft that!

**Comment by isilher** [comment] 2022-08-04 13:41
@izakfilmalter as a temporary solution, I found out that I could restore a partial `app.json` just for the build numbers:

**app.json**

``` json
{
  "expo": {
    "ios": {
      "buildNumber": "2"
    },
    "android": {
      "versionCode": 3
    }
  }
}
```

**app.config.ts**
``` ts
import appBuildNumbers from './app.json';

export default {
  expo: {
    // ... 
    ios: {
      // ...
      buildNumber: appBuildNumbers.expo.ios.buildNumber,
    },
    android: {
      // ...
      versionCode: appBuildNumbers.expo.android.versionCode,
    },
  },
};

**Comment by izakfilmalter** [comment] 2022-08-04 17:00
@isilher Does this work with `auto-increment`?

**Comment by kbrandwijk** [comment] 2022-08-04 17:43
app.config.ts already receives the contents of **app.json** as the config parameter, so you don't have to import it manually.

**app.config.ts**
```js
export default ({ config }) => ({
   ...config,
   // any overrides
})
```

Also, we expect `app.config.ts` to export the contents of the `expo` key, so your code snippet for app.config.ts wouldn't work like you expect it to. See https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs

**Comment by isilher** [comment] 2022-08-08 10:37
> @isilher Does this work with `auto-increment`?

It does! The numbers will be auto-incremented in the `json` file, even when they are the only values present.

> @isilher **app.config.ts** already receives the contents of **app.json** as the config parameter, so you don't have to import it manually.
> 
> **app.config.ts**
> 
> ```js
> export default ({ config }) => ({
>    ...config,
>    // any overrides
> })
> ```

Great tip, thank you. This would also allow me to move back most of the config into `app.json` and only overload the dynamic config keys in `app.config.ts`. 

> Also, we expect `app.config.ts` to export the contents of the `expo` key, so your code snippet for app.config.ts wouldn't work like you expect it to. See https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs

You are right! I missed that when refactoring. Interesting enough, it did work. There might be a safeguard check for this in the config hook?

**Comment by wkozyra95** [comment] 2022-08-09 15:05
Managed versioning landed in the latest cli.
docs: https://docs.expo.dev/build-reference/app-versions/

**Closed by wkozyra95** 2022-08-09 15:05 UTC
Labels: enhancement

**Comment by izakfilmalter** [comment] 2022-08-24 18:03
Just chiming in to say that this works now. I have removed my build numbers from `app.config.ts` and updated my `eas.json` to `"appVersionSource": "remote"` along with `"autoIncrement": true`.

**Comment by ceafive** [comment] 2022-09-20 16:38
How do I autoIncrement 'version'? The docs state that this has to be done manually for submission to production, which means there is still a manual process to be done here? I want to sync my version with the build number. eg. 1.1.6

**Comment by wkozyra95** [comment] 2022-09-20 17:00
@ceafive We intentionally do not provide it, because it would be easy to introduce unexpected behavior when combined with EAS updates  and runtime version policy. We might consider adding that in the future, but it will required appropriate safety nets to avoid potential issues.

> which means there is still a manual process to be done here? 

Not really, there is no requirement to update both version and buildNumber as far as I'm aware.
With that said I still recommend bumping `version` but that value should be bumped only when you are releasing new version to users, which already has a lot of manual steps, so automating that part does not help much eitherway.

**Comment by AAlvarez90** [comment] 2022-09-20 20:44
@ceafive If you want to increase the version of your app (Short Version) (Not the build number), you need to go into the ios directory and find the Info.plist file. Then look for the XML element (CFBundleShortVersionString) and change the value that you see under it. That will change the actual version of the app. This is assuming you are in the bare workflow.
If you are using the managed workflow then updating the app.json update the `version` key inside the `expo` object.
For android, I don't know.
