### ISSUE TITLE
EAS Build fails when using Sentry + Bun

### ISSUE THREAD

**Issue by ocho-cesar** [expo/eas-cli#2064] opened 2023-09-25 19:46 UTC
### Build/Submit details page URL

https://expo.dev/accounts/ocho-co/projects/ocho-app/builds/b1370108-f846-4d85-8baf-701f6c69c35f

### Summary

EAS Build fails when using sentry hooks. It looks like @sentry/cli dependency is not found when using Bun with EAS.

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.8.1 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.12 => 49.0.12
      react: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
    Expo Workflow: managed
```

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

### Error output

```bash
    ...
    export XCODE_VERSION_MINOR\=1430
    export XPCSERVICES_FOLDER_PATH\=OCHO.app/XPCServices
    export YACC\=yacc
    export _WRAPPER_CONTENTS_DIR_SHALLOW_BUNDLE_NO\=/Contents
    export _WRAPPER_PARENT_PATH_SHALLOW_BUNDLE_NO\=/..
    export _WRAPPER_RESOURCES_DIR_SHALLOW_BUNDLE_NO\=/Resources
    export __IS_NOT_MACOS\=YES
    export __IS_NOT_MACOS_macosx\=NO
    export __IS_NOT_SIMULATOR\=YES
    export __IS_NOT_SIMULATOR_simulator\=NO
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/expo/Library/Developer/Xcode/DerivedData/OCHO-asbycgoqcntopbfgrbdamjamarxt/Build/Intermediates.noindex/ArchiveIntermediates/OCHO/IntermediateBuildFilesPath/OCHO.build/Release-iphoneos/OCHO.build/Script-F33BB57CE98346A1ACF87612.sh
Error: spawn /Users/expo/workingdir/build/node_modules/@sentry/cli/sentry-cli ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/expo/workingdir/build/node_modules/@sentry/cli/sentry-cli',
  path: '/Users/expo/workingdir/build/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [
    'debug-files',
    'upload',
    '--force-foreground',
    '',
    '/Users/expo/Library/Developer/Xcode/DerivedData/OCHO-asbycgoqcntopbfgrbdamjamarxt/Build/Intermediates.noindex/ArchiveIntermediates/OCHO/BuildProductsPath/Release-iphoneos'
  ]
}
Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/ocho-cesar/sentry-eas-error-bun

<img width="1167" alt="Screenshot 2023-09-25 at 1 45 14 PM" src="https://github.com/expo/eas-cli/assets/84465617/d4bdf49d-dc11-4834-a117-247f2f654df1">

**Comment by kadikraman** [comment] 2023-09-26 11:58
I can confirm there's a difference when installing the library via bun vs yarn. Not yer sure on the root cause. Both are installing `@sentry/cli@2.17.5`:

| `bun install sentry-expo`    | `yarn add sentry-expo` |
| -------- | ------- |
| <img width="270" alt="Screenshot 2023-09-26 at 10 57 08" src="https://github.com/expo/eas-cli/assets/6534400/155af8a5-8a57-47de-853c-f967c5f5d2ea">    |  <img width="276" alt="Screenshot 2023-09-26 at 10 57 57" src="https://github.com/expo/eas-cli/assets/6534400/3359e9ae-0810-468e-8730-468bfb0e3cfc"> |

**Comment by kadikraman** [comment] 2023-09-26 13:13
Tried this again with `@sentry/cli` directly and getting the same result.

Looks like this is an issue with `bun` not handling binary files defined in the [package.json](https://github.com/getsentry/sentry-cli/blob/master/package.json#L15) correctly. There is an open issue for over at the bun repo: https://github.com/oven-sh/bun/issues/2998

Closing this issue, as it is not something we can fix on `eas-cli`.

**Closed by kadikraman** 2023-09-26 13:13 UTC
Labels: issue accepted

**Comment by byCedric** [comment] 2023-09-26 13:39
@ocho-cesar Maybe you could try working around this issue by adding `trustedDependencies` to your **package.json**, see [my comment here](https://github.com/oven-sh/bun/issues/2998#issuecomment-1735560575).

**Comment by kadikraman** [comment] 2023-09-26 14:32
Can confirm, @byCedric 's suggestion works! 👏 
Note you have to remove your lockfile and node modules first which is why it didn't work for me when I tried this initially.

**Comment by ocho-cesar** [comment] 2023-09-26 20:32
> @ocho-cesar Maybe you could try working around this issue by adding `trustedDependencies` to your **package.json**, see [my comment here](https://github.com/oven-sh/bun/issues/2998#issuecomment-1735560575).

Unfortunately it did not work for me :/

**Comment by kadikraman** [comment] 2023-09-26 22:32
Could you double check you're doing this in the right order? I found it a bit unintuitive as well:

First, update your `package.json` to add:
```sh
"trustedDependencies": ["@sentry/cli"]
```
Second, remove node modules and the bun lockfile:
```sh
rm -rf node_modules
rm bun.lockb
```
Finally run install again
```sh
bun install
```
If it's working correctly you should see something like this after the install script:
<img width="801" alt="Screenshot 2023-09-26 at 23 27 53" src="https://github.com/expo/eas-cli/assets/6534400/3e56f12c-838b-4bdc-89e6-07049930a0ea">

**Comment by erickreutz** [comment] 2023-11-19 13:53
This works for me locally but it does not work when running `eas build`

**Comment by erickreutz** [comment] 2023-11-19 13:59
The problem is the version of bun that eas uses by default. If I set the bun version in eas.json to something higher (like 1.0.7) it will install the cli.

**Comment by chrisharrington** [comment] 2023-11-21 02:20
> The problem is the version of bun that eas uses by default. If I set the bun version in eas.json to something higher (like 1.0.7) it will install the cli.

This worked for me for remote EAS builds. Thanks!
