### ISSUE TITLE
Authentication with Apple Developer Portal failed

### ISSUE THREAD

**Issue by ricardogomez-dev** [expo/eas-cli#2640] opened 2024-10-19 17:44 UTC
### Summary

I am trying to build a development client and I am not able to login to my Apple Account. I'm 100% sure that my email and password are correct, I double checked many times and I'm sure that there is something weird bug happening.

The command that I am running is:

eas build --platform ios --profile development

Error:

<img width="1131" alt="Screenshot 2024-10-19 at 11 40 21 a m" src="https://github.com/user-attachments/assets/62c02700-16a9-44e2-b162-7fa8c3be3216">

### Managed or bare?

Managed

### Environment

development

### Error output

Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios --profile development

**Comment by akhockey21** [comment] 2024-10-19 17:47
I'm also having this issue

**Comment by byCedric** [comment] 2024-10-19 18:37
Duplicate of #2639

**Closed by byCedric** 2024-10-19 18:37 UTC
Labels: needs review
