### ISSUE TITLE
local build fails with fresh app

### ISSUE THREAD

**Issue by whatnottodo** [expo/eas-cli#956] opened 2022-02-03 08:36 UTC
### Summary

can't get app to build locally

### Managed or bare?

managed

### Environment

  EAS CLI 0.46.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
      npm: 8.4.0 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Project workflow: managed

### Error output

[RUN_FASTLANE] › Compiling react-native Pods/RCTTypeSafety » RCTConvertHelpers.mm
[RUN_FASTLANE] › Packaging react-native Pods/React-RCTText » libReact-RCTText.a
[RUN_FASTLANE] › Packaging react-native Pods/ReactCommon » libReactCommon.a
[RUN_FASTLANE] › Packaging react-native Pods/RCTTypeSafety » libRCTTypeSafety.a
[RUN_FASTLANE] › Executing react-native Pods/FBReactNativeSpec » [CP-User] Generate Specs
[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')
[RUN_FASTLANE] ▸ 	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/user/Library/Developer/Xcode/DerivedData/myapp-ctdhmuizdatmvmhaeipgzbxlnrut/Build/Intermediates.noindex/ArchiveIntermediates/myapp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-1D87B5C9FC0450CE76A28799065DB744.sh (in target 'FBReactNativeSpec' from project 'Pods')
[RUN_FASTLANE] ▸ (2 failures)
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE] 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')
[RUN_FASTLANE] 	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/user/Library/Developer/Xcode/DerivedData/myapp-ctdhmuizdatmvmhaeipgzbxlnrut/Build/Intermediates.noindex/ArchiveIntermediates/myapp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-1D87B5C9FC0450CE76A28799065DB744.sh (in target 'FBReactNativeSpec' from project 'Pods')
[RUN_FASTLANE] (2 failures)
[RUN_FASTLANE] Exit status: 65
[RUN_FASTLANE] 
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] |           Build environment           |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] | xcode_path  | /Applications/Xcode.app |
[RUN_FASTLANE] | gym_version | 2.201.2                 |
[RUN_FASTLANE] | sdk         | iPhoneOS15.2.sdk        |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project
[RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how
[RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make
[RUN_FASTLANE] sure your project is set up correctly.
[RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the
[RUN_FASTLANE] the full commands printed out in yellow in the above log.
[RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there
[RUN_FASTLANE] [!] Error building the application - see the log above
[RUN_FASTLANE] Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
[CLEAN_UP_CREDENTIALS] Destroying keychain - /var/folders/6q/g_t0qbk94wl6bxqjswtqdhfm0000gn/T/turtle-v2-1993a432-bfda-438e-b3f4-ce6bf6214ca5.keychain
[CLEAN_UP_CREDENTIALS] Removing provisioning profile

Build failed
Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
    Error: npx exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios --local

**Comment by deanmraz** [comment] 2022-02-03 19:58
I can confirm I am having identical issues

**Comment by wkozyra95** [comment] 2022-02-07 12:48
I run `expo init` and run a local build on app generated from that and I couldn't reproduce that issue. please provide a reproducible example.
Also, you can set `EAS_LOCAL_BUILD_SKIP_CLEANUP` and `EAS_LOCAL_BUILD_WORKINGDIR` as described here https://docs.expo.dev/build-reference/local-builds/#using-local-builds-for-debugging . Raw xcode logs will be available in the specified directory.

**Comment by wkozyra95** [comment] 2022-02-16 08:39
Closing issue, if you are seeing this or a similar problem please create an issue with a reproducible example

**Closed by wkozyra95** 2022-02-16 08:39 UTC
Labels: bug, needs more info
