### ISSUE TITLE
Issue using Expo Update in GitHub Actions, says I haven't ran eas init

### ISSUE THREAD

**Issue by henrymoulton** [expo/eas-cli#1779] opened 2023-04-07 10:54 UTC
### Summary

![my stuff(1)](https://user-images.githubusercontent.com/30093692/230510172-05176e91-b46b-4b40-bf6e-ed526555b5f4.png)

Part of my config has:

```
    "name": "Name",
    "slug": "name",
    "extra": {
      "eas": {
        "projectId": "id"
      }
    },
```

### Managed or bare?

bare

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/henrymoulton/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.12 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
    npmGlobalPackages:
      eas-cli: 3.9.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```
```
expo doctor
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.3.2).                 │
│   You are currently using expo-cli 6.0.8                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
Some dependencies are incompatible with the installed expo package version:
 - @shopify/flash-list - expected version: 1.3.1 - actual version installed: 1.4.1
 - expo-av - expected version: ~13.0.3 - actual version installed: 13.0.2
 - expo-linking - expected version: ~3.3.1 - actual version installed: 3.3.0
 - expo-location - expected version: ~15.0.1 - actual version installed: 15.1.1
 - react-native-maps - expected version: 1.3.2 - actual version installed: 1.4.0
 - react-native-reanimated - expected version: ~2.12.0 - actual version installed: 2.13.0
```

### Error output

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/30093692/230597049-0f1f2d38-5a9a-4db3-8629-dc87db52615a.png">

### Reproducible demo or steps to reproduce from a blank project

Haven't been able to get to a reproducible demo yet.

**Comment by byCedric** [comment] 2023-04-07 11:21
Hi @henrymoulton! Unfortunately, I can't seem to reproduce this error. You can see the full github actions output and the project I've used here: https://github.com/byCedric/expo-monorepo-example/pull/95

Can you provide a repository or repro in any way?

**Comment by byCedric** [comment] 2023-04-11 11:35
Closing in favor of https://github.com/expo/expo-github-action/issues/218

The error was caused because the `working-directory` was omitted. It's not really clear that the default `working-directory` does not apply to plugins in GitHub actions.

```
defaults:
  run:
    working-directory: <sub-path>
```

**Closed by byCedric** 2023-04-11 11:35 UTC
Labels: needs review, eas update

**Comment by moosthuizen42** [comment] 2023-09-05 09:52
Posting here for posterity. Changing
```yaml
- name: 📦 Install dependencies
  run: yarn install

- name: 🚀 Build app
  run: eas build -e preview -p android --non-interactive
```
to
```yaml
- name: 📦 Install dependencies
  working-directory: ./app
  run: yarn install

- name: 🚀 Build app
  working-directory: ./app
  run: eas build -e preview -p android --non-interactive
```
was the solution for us.
