### ISSUE TITLE
EAS build failed Task :app:mergeReleaseAssets FAILED

### ISSUE THREAD

**Issue by samixp02** [expo/eas-cli#915] opened 2022-01-17 15:22 UTC
### Build/Submit details page URL

https://expo.dev/accounts/samixp/projects/med/builds/2e05879b-97a0-4c69-a7a7-99393c94ff46

### Summary

 Task :app:mergeReleaseAssets FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseAssets'.
[stderr] > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
[stderr]    > Could not resolve org.webkit:android-jsc:+.
[stderr]      Required by:
[stderr]          project :app
[stderr]       > Failed to list versions for org.webkit:android-jsc.
[stderr]          > Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
[stderr]             > Could not get resource 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
[stderr]                > Could not GET 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
[stderr]                   > Read timed out

### Managed or bare?

Managed

### Environment

 EAS CLI 0.44.1 environment info:
    System:
      OS: Windows 8.1 6.3.9600
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0. - /mingw64/bin/git
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      expo-dev-client: ~0.8.0 => 0.8.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed

### Error output

![image](https://user-images.githubusercontent.com/20402853/149795022-69d1ea1d-1a60-47a6-8b5d-c952ff224ae8.png)

### Reproducible demo or steps to reproduce from a blank project

eas build -p android

**Comment by kbrandwijk** [comment] 2022-01-17 16:08
Duplicate of #914

**Closed by kbrandwijk** 2022-01-17 16:08 UTC
Labels: bug
