### ISSUE TITLE
Expo eas build fails on android

### ISSUE THREAD

**Issue by MGyahia** [expo/eas-cli#991] opened 2022-02-26 23:51 UTC
### Summary

I made build to the same project that used to pass one month ago but now the build shows errors :

```
Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-6.9-bin.zip
Unzipping /home/expo/.gradle/wrapper/dists/gradle-6.9-bin/2ecsmyp3bolyybemj56vfn4mt/gradle-6.9-bin.zip to /home/expo/.gradle/wrapper/dists/gradle-6.9-bin/2ecsmyp3bolyybemj56vfn4mt
Set executable permissions for: /home/expo/.gradle/wrapper/dists/gradle-6.9-bin/2ecsmyp3bolyybemj56vfn4mt/gradle-6.9/bin/gradle
Welcome to Gradle 6.9!
Here are the highlights of this release:
 - This is a small backport release.
 - Java 16 can be used to compile when used with Java toolchains
- Dynamic versions can be used within plugin declarations
 - Native support for Apple Silicon processors
For more details see https://docs.gradle.org/6.9/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.9/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
[stderr] FAILURE: Build failed with an exception.
[stderr] * Where:
[stderr] Initialization script '/home/expo/.gradle/init.gradle' line: 45
[stderr] * What went wrong:
[stderr] A problem occurred evaluating root project 'artify'.
[stderr] > Could not get unknown property 'url' for object of type org.gradle.api.internal.artifacts.repositories.DefaultFlatDirArtifactRepository.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 27s
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

### Managed or bare?

Bare

### Environment

EAS CLI 0.47.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.29.2.
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      expo-updates: ~0.8.2 => 0.8.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Project Workflow:
      Android: generic
      iOS: managed

### Error output

Could not get unknown property 'url' for object of type org.gradle.api.internal.artifacts.repositories.DefaultFlatDirArtifactRepository.

### Reproducible demo or steps to reproduce from a blank project

eas build --platform android --profile production

**Comment by kbrandwijk** [comment] 2022-02-27 09:33
Are you using `realm` by any chance?

**Comment by MGyahia** [comment] 2022-02-27 10:14
Hi, kbrandwijk, 

_Are you using realm by any chance?_ NO

The project renders well with `expo run:android` command.
I cannot make a local build because I'm a windows user.

The same exact project passed the eas build, 1 month ago.

**Comment by wkozyra95** [comment] 2022-02-28 16:50
Hi, I was able to reproduce the issue, it should be fixed tomorrow.

in a meantime you have 2 options:
- The issue is caused by `flatDir` section in the build gradle, if you don't need it removing that section should fix the issue.
- Adding `rm /home/expo/.gradle/init.gradle` in npm hook will disable maven cache but it also fix the issue

**Comment by MGyahia** [comment] 2022-02-28 20:19
Hi @wkozyra95, I use flatDir to build a local library.
I will wait for the fix. Many thanks for the help.

**Comment by wkozyra95** [comment] 2022-03-01 09:28
should be fixed now

**Closed by wkozyra95** 2022-03-01 09:28 UTC
Labels: bug
