### ISSUE TITLE
App Submission Detail point to wrong URL

### ISSUE THREAD

**Issue by giautm** [expo/eas-cli#844] opened 2021-12-13 10:47 UTC
### Summary

https://github.com/expo/eas-cli/blob/ef566b3f9c01e12e8120801a34e9b64c1959e22e/packages/eas-cli/src/submit/utils/urls.ts#L27

Based on my app, it should be:
`/accounts/${app.ownerAccount.name}/projects/${app.slug}/submissions/${id}`

### Managed or bare?

Both

### Environment

not-related

### Reproducible demo or steps to reproduce from a blank project

none

**Comment by dsokal** [comment] 2021-12-13 11:45
Sorry to say but you haven't filled in the template properly. Even if you think that something is not related to the issue (like the output from `eas diagnostics`) you should provide it anyway. This helps with debugging/looking into the issue. 

Also, one of the most important details is the repro steps. When writing up an issue, you should give an example of what is wrong (or why do you think it's wrong) and the expected behavior. In this case, the exact examples (eas-cli output) would be really helpful because I can't repro the issue. 

Closing the issue again until you fill in the template properly.

**Closed by dsokal** 2021-12-13 11:45 UTC
Labels: bug

**Comment by giautm** [comment] 2021-12-13 12:21
@dsokal It happend in our new CI/CD I can sent image/URl to you privately. How to DM to you?

**Comment by dsokal** [comment] 2021-12-13 12:40
You can find me on the Expo's Discord
