### ISSUE TITLE
Use node-fetch for all network requests: node-fetch and got both installed in eas-cli

### ISSUE THREAD

**Issue by EvanBacon** [expo/eas-cli#32] opened 2020-10-13 12:37 UTC
should settle on one for networking. iirc we've tried to stick to axios or got in expo-cli.

**Comment by ide** [comment] 2020-11-17 18:26
Discussing this with @fson, we want to use node-fetch since `urql` uses it and `node-fetch` implements a stable standard. In its last couple of major releases, it's dropped non-standard features that are convenient to have in Node and is focused on W3C compliance. (For example, the `timeout` option is replaced by `AbortController`.)

`node-fetch` also supports some of our more advanced use cases like multipart form data uploads, which we'll need for EAS Update. The GCS endpoint expects a form data POST request, which we can implement fairly simply with `form-data` and `node-fetch` and just use web APIs. This is not very clever, which is really nice.

**Comment by dsokal** [comment] 2021-09-14 08:48
I looked into getting rid of either of the libraries and I think the best option is to stay with both of them.

1. `node-fetch` is used only for the GraphQL client. We don't use it in other places.
2. We use the `uploadProgress` event from `got` in many places. It doesn't seem to be easily implementable with `node-fetch`. At least I couldn't find any recommended way.
3. `node-fetch` is a really small library - around 200K.
4. I added an eslint rule so we don't use `node-fetch` for anything else than the GraphQL client. See https://github.com/expo/eas-cli/commit/2463e958aa47595e33bda72ca12becc22121519c

**Comment by ide** [comment] 2021-09-14 17:08
`fetch` is the web standard so I could see it being preferable to encourage it everywhere. Node added built-in support for APIs that work with `fetch` like AbortController and URL, so I'd bet on `fetch` more than `got`.

**Comment by LinusU** [comment] 2021-09-15 09:43
The problem is that getting upload progress still isn't fully supported with `fetch`

> 2. We use the uploadProgress event from got in many places. It doesn't seem to be easily implementable with node-fetch. At least I couldn't find any recommended way.

From a bit of googling it seems like the recommended approach is to have readable stream as the body passed to fetch, and then have that stream track how much data is going thru it. I think that this should be possible with node-fetch as well, would be great to add that to the documentation!

**Comment by dsokal** [comment] 2021-09-15 10:07
I still think that we don't need to do anything with this. We mostly use GraphQL for network requests. If using `got` becomes a problem (and I bet it won't) I can be a volunteer to get rid of it.

**Comment by ide** [comment] 2021-09-15 15:56
I think using `got` is fine -- just that we should be using `node-fetch` except where `got` is needed for upload progress.

**Comment by dsokal** [comment] 2021-09-16 07:58
Hmmm, ok, fair enough.

**Comment by kbrandwijk** [comment] 2022-02-11 06:50
> I think using `got` is fine -- just that we should be using `node-fetch` except where `got` is needed for upload progress.

@dsokal @ide `got` has been replaced everywhere except where we track the progress bar for the .tar.gz, download. If that satisfies the original goal, can we close this?

**Comment by ide** [comment] 2022-02-11 16:03
A new PR (see the code signing one) uses got presumably because other command files used it. It should be easy to switch that PR to fetch but I think there is still more to do to make it clear to PR authors to use fetch instead of got.

**Closed** 2022-03-08 14:24 UTC
Labels: 🧹 chore
