### ISSUE TITLE
EAS Update not detecting secrets

### ISSUE THREAD

**Issue by matart15** [expo/eas-cli#2170] opened 2024-01-07 06:06 UTC
### Summary

@byCedric Looks like secrets are not loading when i use ` pnpx eas-cli update --branch preview --message \"update try\"`

I have secrets set.
![Screenshot 2024-01-07 at 14 58 06](https://github.com/expo/expo-cli/assets/17027219/5f2ee606-a9dc-41bd-a1d4-8b07b200e91d)
<img width="795" alt="image" src="https://github.com/expo/expo-cli/assets/17027219/ad11710c-7f32-4048-bfe8-d6031e4db0ed">

then on preview i tried 
```
<Pressable
              onPress={() => {
                Alert.alert("", JSON.stringify(process.env));
              }}
            >
```

This is all there is 

![Screenshot 2024-01-07 at 15 02 03](https://github.com/expo/expo-cli/assets/17027219/55b224a0-a24f-4a10-bec9-f5ab67836a90)

### Managed or bare?

managed

### Environment

Need to install the following packages:
expo-env-info@1.0.5
Ok to proceed? (y)

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      npm: 8.19.4 - ~/workplace/github/specdest-company/mycone/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    Expo Workflow: managed

npx expo-env-info  5.87s user 2.57s system 62% cpu 13.478 total

### Reproducible demo or steps to reproduce from a blank project

1. create project
2. set secrets
3. create eas update
4. add some code to see process.env ( if my understanding is correct secrets should be there )
```ts
<Pressable
              onPress={() => {
                Alert.alert("", JSON.stringify(process.env));
              }}
            >
```
5. update pnpx eas-cli update --branch preview --message \"update try\"

**Comment by szdziedzic** [comment] 2024-01-10 09:22
Hi there!

Sorry for making it confusing, but secrets are only used when doing your EAS cloud builds at the moment. The `eas update` command uses env vars available in your local environment and doesn't have access to secrets stored on EAS servers. Here are the docs about how you can use env variables when using EAS Update: https://docs.expo.dev/eas-update/environment-variables/.

With that being said, we have some plans to improve the situation regarding env vars this year to make it easier to work with/less confusing. I think that if you are waiting for this it would be best if you follow [our changelog](https://expo.dev/changelog) to stay up to date with all EAS changes 🙂 

I'm going to close the issue because it technically is not a bug, but a way this functionality works at the moment. Please, let me know if you have any more questions!

**Closed by szdziedzic** 2024-01-10 09:22 UTC
Labels: needs review

**Comment by matart15** [comment] 2024-01-11 02:12
@szdziedzic 
If that is the case. We are back to .env is not being loaded on `eas update` problem

I have `.env` file. it is working without problem on `expo dev`.

![Screenshot 2024-01-11 at 11 10 55](https://github.com/expo/eas-cli/assets/17027219/0baa7688-c24f-4068-bd17-86b314ccb16f)


But when i use `expo update`


![Screenshot 2024-01-07 at 15 02 03](https://github.com/expo/expo-cli/assets/17027219/55b224a0-a24f-4a10-bec9-f5ab67836a90)

**Comment by matart15** [comment] 2024-01-11 02:15
Again issue is closed. I am creating new one.

https://github.com/expo/eas-cli/issues/2174

**Comment by noctivityinc** [comment] 2024-03-09 01:56
@szdziedzic wow this is a pretty big deal.  Not being able to use `eas update` and expo secrets together kind of cripples the entire functionality (and reason we are paying) for eas update.  When do you expect to have a solution for this?  Any reason why `eas update` cannot pull down the secrets when it's compiling the update (or interpolate them during the push up to eas?

**Comment by 11kodykay11** [comment] 2024-04-25 14:33
This is a big deal. I spent almost 2 days just to figure out why eas update screwing my test flight build.

**Comment by matheuscouto** [comment] 2024-07-11 20:43
From what I understand secrets aren't meant to be seen/retrieved on the client side, everything there should be considered public info since anyone can retrieve those and read as plaintext by scraping the app. If you need a key to fetch some 3rd party data then you should create a service that pulls that on behalf of the user and return it, so the user never gets his hand on the key.

And if you really need that info on the client-side then that data most likely isn't a secret and you can add it to your eas.json profile on the env property. https://docs.expo.dev/build/eas-json/#environment-variables
