### ISSUE TITLE
Can not specify image name for ios builds

### ISSUE THREAD

**Issue by nwpharama-arch** [expo/eas-cli#1562] opened 2022-12-05 16:15 UTC
### Summary

Trying to use either 'default' or 'latest' as the build target  in the eas.json results in following error.
" InvalidEasJsonError: Specified build image 'default' is not recognized."

The command used was "eas build -p ios --profile production --clear-cache"

This happened with both eas-cli 2.8 and 2.9. 

Using powershell terminal in Visual Code on Windows OS

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version
    npmPackages:
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: bare

### Error output

InvalidEasJsonError: Specified build image 'default' is not recognized. Please update your EAS CLI and see https://docs.expo.dev/build-reference/infrastructure/ for supported build images.

### Reproducible demo or steps to reproduce from a blank project

Using the following eas.json
{
  "build": {
    "preview": {
      "android": {
        "buildType": "apk"
      }
    },
    "release": {},
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "production":{"channel": "production"},
    "ios":{"image":"default"}
  }}

and use the following command

eas build -p ios --profile production --clear-cache

will produce the error

**Comment by dsokal** [comment] 2022-12-06 08:48
Hi,

I cannot reproduce the issue.

1. `eas.json` you provided is probably not the one you're actually using locally. You said you're using `eas build -p ios --profile production` for building, and yet the `production` profile doesn't have the image changed.
2. I'm not sure how you generated the environment info. You should share the output from `eas diagnostics`. The one you shared looks slightly different than the one I just saw on my machine.

**Comment by wkozyra95** [comment] 2022-12-06 11:12
The error message is incorrect, but the reason for failure is still invalid eas.json

You created build profile named "ios" and specified "image" inside, build profiles do not support image in the root, so it's either it should be
`"ios": {"ios":{"image":"default"}}`
or more likelly you wanted to add that to production profile
`"production":{"channel": "production", "ios":{"image": "default"}},`

**Comment by szdziedzic** [comment] 2022-12-06 13:16
Hi,

PR fixing incorrect error message was merged and it will be released soon 🎉

**Closed by szdziedzic** 2022-12-06 13:16 UTC
Labels: needs more info, eas build
