### ISSUE TITLE
EAS build fail (project was previously on Expo SDK 42, updated to SDK 44)

### ISSUE THREAD

**Issue by lottemarines** [expo/eas-cli#913] opened 2022-01-16 02:07 UTC
### Build/Submit details page URL
iOS
https://expo.dev/accounts/lottemarines/projects/hiroyuki-voice/builds/553973e4-1d80-4443-bf33-edf34a186c7d
Android
https://expo.dev/accounts/lottemarines/projects/hiroyuki-voice/builds/4993e6cb-2b26-4ed8-a424-b8933a9ff772

### Summary

After updating from Expo 42 to Expo 44, I ran the EAS build and it failed on both iOS and Android.
I don't think there is a problem with the local code because the EAS build succeeds after I move all the code of the failed app to an empty app I created from scratch. (All files except app.json and nodemodule)

Is there any special procedure needed to migrate from expo build to eas build?

### Managed or bare?

Managed

### Environment

```  
$ eas diagnostics

  EAS CLI 0.44.1 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nodebrew/current/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nodebrew/current/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Project workflow: managed

```  

### Error output
Submission Details (Android)

``` expo-store-review (5.1.0)
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated
[stderr] error Unable to resolve module ../config/env from /root/workingdir/build/screens/MyPageScreen.tsx:
[stderr] None of these files exist:
[stderr]   * config/env(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr]   * config/env/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr] > 1 | import React, { useState, useEffect } from "react";
[stderr]   2 | import {
[stderr]   3 |   Dimensions,
[stderr]   4 |   Platform,.
``` 

Submission Details (iOS)

```
 ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/app-gfczuwoxhhirjpelxqecjxyrawps/Build/Intermediates.noindex/ArchiveIntermediates/app/IntermediateBuildFilesPath/app.build/Release-iphoneos/app.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'app' from project 'app')
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/app-gfczuwoxhhirjpelxqecjxyrawps/Build/Intermediates.noindex/ArchiveIntermediates/app/IntermediateBuildFilesPath/app.build/Release-iphoneos/app.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'app' from project 'app')
(1 failure)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.185.1                 |
| sdk         | iPhoneOS15.0.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[stderr] [!] Error building the application - see the log above
Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.

```  

### Reproducible demo or steps to reproduce from a blank project

I can't reproduce it from an empty project.

```  
$ rm -rf node_modules
$ yarn
$ eas build --profile=production -p all --no-wait --auto-submit --clear-cache
```  

### Screenshots(fyi. Submission Details (Android))
![スクリーンショット 2022-01-16 13 30 04](https://user-images.githubusercontent.com/19564723/149647332-9efb2269-6fcf-40b0-adb1-9cd763a186b3.png)
![スクリーンショット 2022-01-16 13 31 24](https://user-images.githubusercontent.com/19564723/149647345-a25b1cc0-8900-4183-9f59-2a8ccf21c6e2.png)

**Comment by dsokal** [comment] 2022-01-17 08:55
I'm closing the issue. It doesn't seem to be a problem with EAS Build. 

1. You noticed that you're able to build the project if you move the code to a blank project. Because of that, I'm 99.9% sure this is a matter of your original project's configuration.
2. EAS Build cannot build your project if it can't be built locally. You can run `expo prebuild` and try to build it with either Android Studio or Xcode.
3. FWIW this is the guide on migrating from `expo build` - https://docs.expo.dev/build-reference/migrating/
4. The reproducible demo you provided is actually not a demo. See https://docs.expo.dev/workflow/debugging/

**Closed by dsokal** 2022-01-17 08:55 UTC
Labels: bug
